using UnityEngine;

public enum ItemName
{
   SIMPLE_WALL = 0,
   GEM_WALL,
   YELLOW_WALL,
   PINK_WALL,
   BLUE_WALL,
   
   GEM_FLOOR,
   PINK_FLOOR,
   BLUE_FLOOR,
   SIMPLE_FLOOR,
   
   WHITE_CEILING,
   GEM_CEILING,
   PINK_CEILING,
   YELLOW_CEILING,
   BLUE_CEILING,
   
   BLUEBERRY_BED,
   GEM_BED,
   NORMAL_BED,
   WHITE_PINK_BED,
   BLUE_BED,
   YELLOW_ORANGE_BED,
   RAINBOW_BED,
   BLUE_WHITE_BED,
   GREEN_BED,
   STRAWBERRY_BED,
   PINK_FLOWER_BED,
   WHITE_FLOWER_BED,
   
   GEM_SEWING_DESK,
   WHITE_SEWING_DESK,
   NORMAL_SEWING_DESK,
   
   BROWN_SHELF,
   GEM_SHELF,
   WHITE_SHELF,
   DESIGN_WHITE_SHELF,
   CREAM_WHITE_SHELF,
   BROWN_SHELF_MEDIUM,
   WHITE_SHELF_MEDIUM,

   PLUSHIE_BROWNIE,
   PLUSHIE_CREAMIE,
   PLUSHIE_BUBBLEGUM,

   BUTTON_BLACK,
   BUTTON_WHITE,
   BUTTON_BROWN,

   THREAD_SPOOL_BLACK,
   THREAD_SPOOL_WHITE,
   THREAD_SPOOL_BLUE,

   COINS_PREMIUM,
   COINS_BASIC
}
