using UnityEngine;

public enum DecorItemName
{
   SIMPLE_WALL = 0,
   GEM_WALL,
   YELLOW_WALL,
   PINK_WALL,
   BLUE_WALL,
   
   GEM_FLOOR,
   PINK_FLOOR,
   BLUE_FLOOR,
   SIMPLE_FLOOR,
   
   WHITE_CEILING,
   GEM_CEILING,
   PINK_CEILING,
   YELLOW_CEILING,
   BLUE_CEILING,
   
   BLUEBERRY_BED,
   GEM_BED,
   NORMAL_BED,
   WHITE_PINK_BED,
   BLUE_BED,
   YELLOW_ORANGE_BED,
   RAINBOW_BED,
   BLUE_WHITE_BED,
   GREEN_BED,
   STRAWBERRY_BED,
   PINK_FLOWER_BED,
   WHITE_FLOWER_BED,
   
   BROWN_SHELF,
   GEM_SHELF,
   WHITE_SHELF,
   DESIGN_WHITE_SHELF,
   CREAM_WHITE_SHELF,
   GEM_SEWING_DESK,
   WHITE_SEWING_DESK,
   NORMAL_SEWING_DESK
}
